### ISSUE TITLE
Drill down for Month [TXT] in archive shows the annual report 

### ISSUE THREAD

**Issue by uktricky** [neoground/neowx-material#10]
Thank you for making it easier to see the TXT report on month 

When I drill down into my 2021-03 report I am seeing the annual outputs - rather than the traditional month breakdown?

http://10.1.2.22/weewx/archive/NOAA-2021-03.txt

                     CLIMATOLOGICAL SUMMARY for year 2021

NAME: 
ELEV: 738 feet    

                                       TEMPERATURE (Â°C)

                              HEAT    COOL                              MAX    MAX    MIN    MIN
          MEAN   MEAN         DEG     DEG                                >=     <=     <=     <=
 YR  MO   MAX    MIN    MEAN  DAYS    DAYS      HI  DAY     LOW  DAY     30      0      0    -20
------------------------------------------------------------------------------------------------
2021 01
2021 02
2021 03    8.3    5.2    6.6   23.8    0.0    10.2   21     5.0   21      0      0      0      0
2021 04
2021 05
2021 06
2021 07
2021 08

**Comment by neoground** [comment]
The monthly template had the wrong content. I fixed it in the upcoming release.
You may need to remove all generated txt files and run "wee_reports" (found in weewx's bin directory) to re-generate them with the correct template.
