### ISSUE TITLE
v1.8 - graph of ET

### ISSUE THREAD

**Issue by swirlingair** [neoground/neowx-material#11]
Graph of ET in v1.8 is appearing as a text box instead of a graph.

ET does appear correctly in the text box section.
![et-graph-error](https://user-images.githubusercontent.com/5019948/112129941-d09e9400-8bbf-11eb-9ba5-88387b64b28a.png)

**Comment by neoground** [comment]
Yes, there is a bug in the current version. It's fixed in the next release 👍

**Comment by swirlingair** [comment]
Thank you 👍
