### ISSUE TITLE
v1.8 - various 'apparent temperatures'

### ISSUE THREAD

**Issue by swirlingair** [neoground/neowx-material#12]
Would it be possible to add appTemp as a 3rd line in the 'Wind Chill' graph, and then to relabel that graph as 'Wind Chill, Heat Index, Apparent Temperature', please, instead of it being a separate graph?  I regard all of these 3 quantities as types of 'feels-like' temperatures, taking account of various met conditions.

**Comment by neoground** [comment]
Yes, this makes sense. I will change this is in the next release. Thank you 👍

**Comment by swirlingair** [comment]
That's excellent; thank you 👍
