### ISSUE TITLE
v1.9 - appTemp titles

### ISSUE THREAD

**Issue by swirlingair** [neoground/neowx-material#13]
For the variable appTemp, would it be possible to rename the text box, and change the label on the Wind Chill/Heat Index/appTemp combined graph, to Apparent Temp, please?

**Comment by neoground** [comment]
A good idea, thank you. It will be available in the next release 👍 

I already included the section in the docs. See the "charts titles" section at the end of: https://neoground.com/docs/neowx-material/config.charts
