### ISSUE TITLE
appTemp on 'Yesterday' page

### ISSUE THREAD

**Issue by swirlingair** [neoground/neowx-material#15]
On the 'Yesterday' page, on the combined Wind Chill/Heat Index/appTemp graph, appTemp is shown for today as well as the previous days.  Can this be corrected, please?
![yesterday-appTemp](https://user-images.githubusercontent.com/5019948/112278556-df964c80-8c7a-11eb-9eac-323d9cdbf653.png)

**Comment by neoground** [comment]
There was a bug for charts with more than 2 data series on the yesterday page. It's fixed in the next release.
