### ISSUE TITLE
Incorrect italian words in Translation section of skin.conf

### ISSUE THREAD

**Issue by Attilio57** [neoground/neowx-material#19]
Using language = it option in skin.conf I found two error in italian translation of english counterparties and asuggestion for a different translation of "set"

[[[it]]]
            ...
            rise = Levata
            ...
            set = Caduta (you can use Tramonto. Tramonto and Caduta are both used but the former is used more often)
            ...
            summer_solstice = Solstizio estate

Obviously I can change them by myself into the file but I will point them out anyway for a future release if you decide to correct the file.

I'll try to translate all the other words (temperature, humidity, rain and so on) as I did in the neowx previous version but it's a my web site customization that I don't expect to be done by anyone :-)

**Comment by alek911** [comment]
Ciao @Attilio57 , come posso contattarti? Ho letto che stavi facendo la traduzione e vorrei chiederti un aiuto. Sono nuovo di weemx e di questa skin. non riesco a mettere le altre label in italiano. Sei disponibile?
Ti ringrazio

**Comment by Attilio57** [comment]
Ciao. Spero di aver compreso la tua esigenza. Ti allego le traduzioni che ho utilizzato nello skin.conf nella cartella Season e quelle dello skin.conf di neowx. Se non è quanto richiesto o hai altre domande contattami.
[skin_conf_weewx.txt](https://github.com/user-attachments/files/16648083/skin_conf_weewx.txt)
[skin_conf_neowx.txt](https://github.com/user-attachments/files/16648089/skin_conf_neowx.txt)

**Comment by Attilio57** [comment]
Ciao. Spero di aver compreso la tua esigenza. Ti allego le traduzioni che ho utilizzato presenti nello skin.conf nella cartella Season e quelle dello skin.conf di neowx che ho utilizzato.
[skin_conf_weewx.txt](https://github.com/user-attachments/files/16648083/skin_conf_weewx.txt)
[skin_conf_neowx.txt](https://github.com/user-attachments/files/16648089/skin_conf_neowx.txt)

**Comment by alek911** [comment]
Grazie Attilio, sei stato gentilissimo! Stasera spulcio bene. Nel frattempo
qualcosa sono riuscito a fare ma ho già notato che alcuni termini che hai
usato sono sicuramente più precisi di quelli che sono riuscito a inserire
io e quindi li sostituirò!
Ho visto dai file che hai aggiunto anche delle cose: se la tua stazione è
pubblica puoi darmi il link per vedere il risultato finale?
Sto mettendo in piedi la stazione meteo per la baita di mio papà ed è la
mia prima esperienza con queste cose. Ogni spunto possibile mi sarebbe
davvero comodo.

Ti ringrazio!

Il dom 18 ago 2024, 12:49 Attilio57 ***@***.***> ha scritto:

**Comment by Attilio57** [comment]
Purtroppo la mia pagina web è al momento offline per via di problemi con l'HD esterno su cui era installato gran parte del file system. Devo trovare il tempo di lavorarci. Considera che ho utilizzato weewx per un sito con immagine webcam, storico dati e effemeridi celesti e per inviare dati ad alcune associazioni meteo. Con l'estensione neowx ho prodotto la versione mobile. Inoltre tramite script inviato dati ad amici via email. Rimettere su il tutto non è banale, purtroppo. Appena sarà disponibile ti avviserò. Nel frattempo in bocca al lupo per la tua installazione.
