### ISSUE TITLE
Charts are not starting properly

### ISSUE THREAD

**Issue by magnum61** [neoground/neowx-material#3]
Now that the first problem fixed and the template is running, i do have another one. Sorry for maybe stupid questions

The date is correct, but the charts are off from the real date:

This is how it looks like. Unfortunately i cannot share as it's installed in my LAN only.
I live in Germany and it's currently Friday 17:05. This is shown in the text boxes properly, but the chart is off the track showing something on thursday (yesterday)

![grafik](https://user-images.githubusercontent.com/59759323/110966359-77c83380-8355-11eb-9d17-c7692c6c64d9.png)

It's not even an hour (the raspberry does have the correct timezone) but somethin in between

**Comment by neoground** [comment]
There seems to be a problem with incomplete data which is displayed somehow wrong on the graphs.

Are you using the simulator weather station or "real" data? Does the tooltip on hover also show the wrong date / time?

**Comment by magnum61** [comment]
I am using a real station with the interceptor accessing the data from my ecowitt-client. 
I've just changed back to the default WeeWX skin and the problem is not there:

![grafik](https://user-images.githubusercontent.com/59759323/110970557-28383680-835a-11eb-98a1-f4c4a2b5187e.png)

For the tooltip question i will check it on next iteration. I've also deleted the database to start fresh, but that did not change it

**Comment by magnum61** [comment]
Update: 

Changed back to Material skin, restarted WeeWX and waited a few minutes.

Charts are displaying it incorrect again.

**Comment by neoground** [comment]
The graphs of neowx-material use timespan-calculations provided by weewx. If in the timespan (in this case 24h) data is missing it's displayed incorrectly. I guess that's the problem here. Other users which are using the skin with "complete" current data don't seem to have these problems (as far as I know).

I fixed a similar bug on the archive pages where data was missing as well. I will apply this on the general pages as well.

**Comment by neoground** [comment]
Please try the latest version 1.5. It contains the mentioned adjustments. If it doesn't work please reopen this issue.

**Comment by magnum61** [comment]
That sorted the problem out. Charts are displayed now correctly:

![grafik](https://user-images.githubusercontent.com/59759323/110980523-37bd7c80-8366-11eb-8083-cd4febba2e69.png)

Many thanks for that quick update!
