### ISSUE TITLE
SoilMoist / SoilTemp charts

### ISSUE THREAD

**Issue by groetg** [neoground/neowx-material#39]
I am using WatherLink Live driver in weewx. I have added SoilMoisture and SoilTemp sensors.

The Soilmoist data i see in the left column, but I also want the data in a chart at the right column, but there is no chart coming up. What am I doing wrong?

[Station: Oosterweg Nrd, NL](http://www.buroscope.nl/weerstation)

![neo1](https://user-images.githubusercontent.com/25323738/144721925-b71fece8-fc68-4d8f-b17b-cb88fc01abf3.PNG)
---
![neo2](https://user-images.githubusercontent.com/25323738/144721937-216bb0b5-58ce-4d1f-a0b3-6fd48674062b.PNG)
---
![neo3](https://user-images.githubusercontent.com/25323738/144721940-07607fa9-d92c-40d9-8c4c-53a1ca2edf22.PNG)

**Comment by groetg** [comment]
It is solved

**Comment by obstbauer** [comment]
Hi, I have the same problem. How do you solved it?
Thanks!

**Comment by groetg** [comment]
In index.html.tmpl:
  // Other sensors
  #if $day.soilTemp1.has_data
  $getChartJsCode("soilTemp1", "soilTemp1chart", "area", "soilTemp1", "avg")
  #end if

  #if $day.soilMoist1.has_data
  $getChartJsCode("soilMoist1", "soilMoist1chart", "area", "soilMoist1", "avg")
  #end if
