### ISSUE TITLE
new issue with latest update

### ISSUE THREAD

**Issue by magnum61** [neoground/neowx-material#4]
After fixing the first problem with the graphs my installation now shows another minor issue:

![grafik](https://user-images.githubusercontent.com/59759323/110987874-077adb80-8370-11eb-9bd0-8ccf91596867.png)

I've verified the source code and compared it with the TMPL file, it's the same. So this text block is shown which should be a tooltip:
```

           <h5 class="h5-responsive indigo-text">Barometer

                <i class="wi wi-direction-up-right" title="Trend: 1.3 mbar" data-toggle="tooltip"></i>
              #elseif 1.3398078924278707 == 0
                <i class="wi wi-direction-right"></i>

            </h5>
```

**Comment by neoground** [comment]
Sorry, just a small typo. I will fix it in the current release in the next few minutes.

To manually fix this just change "elseif" to "else if" in index.html.tmpl, line 72.

**Comment by magnum61** [comment]
No prob, shit happens ;-)

Thanks

**Comment by magnum61** [comment]
adding the space made the trick

![grafik](https://user-images.githubusercontent.com/59759323/110988976-8886a280-8371-11eb-9da5-c96d685e0eff.png)
