### ISSUE TITLE
A question: What is appTemp?

### ISSUE THREAD

**Issue by danrhjones** [neoground/neowx-material#58]
I have looked around, I checked the code, checked past issues, but I can't work out what appTemp actually is?

**Comment by stalkerGH** [comment]
Maybe it is too late for reply but take a look here:

https://groups.google.com/g/weewx-user/c/FOcDKr8FH2E
https://en.wikipedia.org/wiki/Apparent_temperature

I cite from Wikipedia: "Apparent temperature, also known as feels like, is the temperature (...) by the combined effects of air temperature, relative humidity and wind speed."
