### ISSUE TITLE
Change cloudbase to feet - I'm a pilot

### ISSUE THREAD

**Issue by nzkiwi68** [neoground/neowx-material#75]
I know, New Zealand is a metric country too, but, as a pilot, I just so think of cloud heights in feet and wind speed in knots.

Any chance of a mod that allows for the wind speed to be shown in knots and especially the cloud base in feet?

Thanks!

Love the skin.

**Comment by neoground** [comment]
The units displayed in the reports are provided by Weewx, which allows you to configure the entire unit system or modify individual values, such as wind speed and cloud base, no matter in which unit they're stored in the database. For tailored adjustments to your preferences, please refer to the Weewx Customization Guide at [changing unit systems](https://weewx.com/docs/customizing.htm#how_to_change_units).

To display wind speed in knots and cloud base in feet in Weewx, you can add the following settings to your `weewx.conf` file under the `[StdReport]` section:

```conf
[StdReport]
    [[Units]]
        [[Groups]]
            # Set wind speed unit to knots
            group_speed = knot
            # Set cloud base height unit to feet
            group_altitude = foot
```

**Comment by nzkiwi68** [comment]
Thank you so much.

Sorry for the trouble. I made the changes in weewx.conf and did a reset of the HTML files (as if I was changing to a new skin) and now I have wind speed in knots and cloudbase in feet.

Thanks again!
