### ISSUE TITLE
Monthly NOAA data is not available in Archive

### ISSUE THREAD

**Issue by uktricky** [neoground/neowx-material#8]
TXT report is available for the year but no monthly in year summary data

**Comment by uktricky** [comment]
I've just noticed that you can get to the monthly view from More under the Year Archive then drill down into the Month "title" in each cell to see the [TXT] box

Not very clear? be good to have the old style option to drill into the data also

**Comment by neoground** [comment]
You're right, it's not that clear. I updated the layout and improved the whole archive appearance in the upcoming release 👍
