### ISSUE TITLE
Contact with Sven (author of neowx-material and other projects)

### ISSUE THREAD

**Issue by stalkerGH** [neoground/neowx-material#81]
I would like to ask if anyone managed to get in touch with Sven, the author of the neowx-material skin and other projects. I've been trying unsuccessfully for some time. I know he's active, but as you may have noticed, he doesn't respond to new issues nor comment them.

It's a rather poor way to build a community around any project, however promising, don't you think?

**Comment by seehausen** [comment]
I already created a fork https://github.com/seehase/neowx-material where I included some open PR
maybe "WE" can continue working together here?

**Comment by stalkerGH** [comment]
@seehausen Thank you, I know your fork and using it actively (for testing purposes as far because I'm using my weather station in test mode yet). I appreciate your improvements!

But I'm little bit dissapointed and surprised that author is constantly silent. I'd like to check his other project, InfinitySky (https://github.com/neoground/InfinitySky) but I'm afraid I have to abandon it on the very beginning. If something will not work, I won't be able to deal with problem. 

Sorry for fussing. This is definitely not a issue :)

**Comment by stalkerGH** [comment]
No reaction from author for almost 5 months, closing the issue.
