### ISSUE TITLE
Can the templates be extended to handle the extra temp/humidity data

### ISSUE THREAD

**Issue by uktricky** [neoground/neowx-material#9]
Extended data set for 
extraTemp4, extraTemp5, extraTemp6
extraHumid4, extraHumid5, extraHumid6

These go from 1-8 in each so would be good to have them checked for each current, yesterday, month etc
To show values and graphs if data exists

**Comment by neoground** [comment]
These values were missing. I also added the missing inTemp / inHumidity charts. In the upcoming release all data types are supported and displayed if data is available 👍
